; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#612de53
framework = arduino
build_flags =
	-Wall	-Wextra
	-DUSE_TINYUSB
lib_deps =
	https://github.com/homy-newfs8/libps2#v0.1.2
	; symlink://../libps2
lib_ignore =
	SdFat - Adafruit Fork

[env:seeed_xiao_rp2040]
board = seeed_xiao_rp2040
board_build.core = earlephilhower
board_build.arduino.earlephilhower.usb_product = PS/2 to USB Ver1.0
monitor_speed = 115200
